import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
    <div className="p-5 text-center bg-light">
        <h1 className="mb-3">WELCOME TO LAZY DISPOSAL</h1>
        <h4 className="mb-3">Do little things and save the world!</h4>
    </div>
    </header>

    <div className="container">
      <p>
      We help you easily get rid of everything that you should not throw in the bin! Lightbulbs, batteries, broken appliances, and many more!
      <br></br>
      Or check out the map and help your neighbours get rid of their items! We'll direct you to the closest recycling centre!
      </p>
        <b>How to do it?</b>
        <ul>
          <li>Go to the <a href="/form"> "Drop Item" page</a> and fill out the form with the items you want to get rid of </li> 
          <li>Go to the <a href="/pickup"> "Pickup" page</a> and see the item you just added! </li>
          <li>You can book any item on the list. Click "collected" when you collect the item(s).</li>
          </ul>
    </div>

      <footer className={styles.footer}>
        <a
          href="https://www.convex.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/convex.svg" alt="Convex Logo" width={90} height={18} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
